/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rsamaurinin;

import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.Random;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author EMOA
 */
public class ladoCliente extends javax.swing.JFrame {

    private BigInteger p;
    private BigInteger q;
    private BigInteger N;
    private BigInteger phi;
    private BigInteger e;
    private BigInteger d;
    private int bitlength = 1024;
    private Random r;
    static ServerSocket ss;
    static ServerSocket ss2;
    static ServerSocket ss3;
    static Socket s;
    static Socket s2;
    static Socket s3;
    static DataInputStream dis;
    static DataOutputStream dos;
    static DataOutputStream dosN;
    static DataOutputStream dosD;
    static DataInputStream disN;
    static DataInputStream disD;

    /**
     * Creates new form ladoCliente
     *
     */
    public ladoCliente() {
        initComponents();
        //Color JFrame
        this.getContentPane().setBackground(Color.decode("#A7D3A6"));
        jTextArea1.setVisible(false);
        r = new Random();
        p = BigInteger.probablePrime(bitlength, r);
        q = BigInteger.probablePrime(bitlength, r);
        N = p.multiply(q);
        phi = p.subtract(BigInteger.ONE).multiply(q.subtract(BigInteger.ONE));
        e = BigInteger.probablePrime(bitlength / 2, r);
        while (phi.gcd(e).compareTo(BigInteger.ONE) > 0 && e.compareTo(phi) < 0) {
            e.add(BigInteger.ONE);
        }
        d = e.modInverse(phi);
    }

    public ladoCliente(BigInteger e, BigInteger d, BigInteger N) {
        this.e = e;
        this.d = d;
        this.N = N;
    }

    public BigInteger bigIntObtenerD() {
        return (d);
    }

    public BigInteger bigIntObtenerN() {
        return (N);
    }

    // Encrypt message
    public byte[] encrypt(byte[] message) {
        return (new BigInteger(message)).modPow(e, N).toByteArray();
    }

    // Decrypt message
    static public byte[] decrypt(byte[] message, BigInteger valD, BigInteger valN) {
        return (new BigInteger(message)).modPow(valD, valN).toByteArray();
    }

    private static String bytesToString(byte[] encrypted) {
        String test = "";
        for (byte b : encrypted) {
            test += Byte.toString(b);
        }
        return test;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtLadoClienteVentana = new javax.swing.JTextArea();
        txtMensajeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEnviarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLadoClienteVentana.setEditable(false);
        txtLadoClienteVentana.setBackground(new java.awt.Color(207, 231, 155));
        txtLadoClienteVentana.setColumns(20);
        txtLadoClienteVentana.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtLadoClienteVentana.setRows(5);
        txtLadoClienteVentana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(212, 198, 133), 3, true));
        jScrollPane1.setViewportView(txtLadoClienteVentana);

        txtMensajeCliente.setBackground(new java.awt.Color(207, 231, 155));
        txtMensajeCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txtMensajeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMensajeClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel1.setText("CHAT RSA DEL CLIENTE");

        btnEnviarCliente.setBackground(new java.awt.Color(247, 239, 129));
        btnEnviarCliente.setText("Enviar");
        btnEnviarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel2.setText("Escribe tu mensaje aquí");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(207, 231, 155));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 198, 133), 3));
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(247, 239, 129));
        jButton1.setText("Mostrar Descifrado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMensajeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensajeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviarCliente)
                    .addComponent(jLabel2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarClienteActionPerformed
        try {

            String mensajeserver = "";
            mensajeserver = txtMensajeCliente.getText();
            txtMensajeCliente.setText("");
            //showMessageDialog(null, bytesToString(mensajeserver.getBytes()));
            byte[] arres = encrypt(mensajeserver.getBytes());
            byte[] desencriptado = decrypt(arres, bigIntObtenerD(), bigIntObtenerN());
            String bytes = bytesToString(arres);
            String des = new String(desencriptado);
            System.out.println("Bytes enviados: " + bytesToString(arres));
            System.out.println("Decrypted String: " + new String(desencriptado));
            //showMessageDialog(null, Arrays.toString(arres));
            dos.writeUTF(Arrays.toString(arres));
            String N = bigIntObtenerN().toString();
            String D = bigIntObtenerD().toString();
            System.out.println("Este es el valor de N: " + bigIntObtenerN().toString());
            System.out.println("Este es el valor de d: " + bigIntObtenerD().toString());
            dosN.writeUTF(bigIntObtenerN().toString());
            dosD.writeUTF(bigIntObtenerD().toString());
            txtLadoClienteVentana.setText(txtLadoClienteVentana.getText() + "\n Usted: " + arres);
            jTextArea1.setText(jTextArea1.getText() + "\n Mensaje descifrado (Bytes): " + bytes + "\n Mensaje descifrado: " + des + "\n N: " + N + "\n D: "+ D + "\n----------------------------------------------------------------------------------------------------------------------------------- ");

        } catch (Exception e) {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarClienteActionPerformed

    private void txtMensajeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensajeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMensajeClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ladoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ladoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ladoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ladoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ladoCliente().setVisible(true);
            }
        });

        try {
            String msjentrada = "";
            String msjRsaD = "";
            String msjRsaN = "";
            s = new Socket("127.0.0.1", 1449);
            s2 = new Socket("127.0.0.1", 1450);
            s3 = new Socket("127.0.0.1", 1451);
            dis = new DataInputStream(s.getInputStream());
            disN = new DataInputStream(s2.getInputStream()); // N va por el puerto 1450
            disD = new DataInputStream(s3.getInputStream()); // D va por el puerto 1451
            dos = new DataOutputStream(s.getOutputStream());
            dosN = new DataOutputStream(s2.getOutputStream());
            dosD = new DataOutputStream(s3.getOutputStream());

            while (!msjentrada.equals("Exit")) {

                //ladoCliente ld = new ladoCliente();
                msjentrada = dis.readUTF(); //-- aqui si lo hace
                System.out.println("Este es el mensaje del servidor:" + msjentrada); //--- 
                msjRsaN = disN.readUTF();
                msjRsaD = disD.readUTF();
                BigInteger rsaN = new BigInteger(msjRsaN);
                BigInteger rsaD = new BigInteger(msjRsaD);
                String joinedMinusBrackets = msjentrada.substring(1, msjentrada.length() - 1);
                // byte[] bdes = msjentrada.getBytes();
                String[] resplit = joinedMinusBrackets.split(", ");
                byte[] arrenc = new byte[resplit.length];
                for (int i = 0; i < resplit.length; ++i) {
                    arrenc[i] = Byte.parseByte(resplit[i]);
                }
                System.out.println("Bytes recibidos: " + arrenc);
                //showMessageDialog(null, Arrays.toString(arrenc));
                System.out.println("Recibí este valor de D: " + msjRsaD);
                System.out.println("Recibí este valor de N: " + msjRsaN);
                byte[] desencriptado = decrypt(arrenc, rsaD, rsaN);
                String bytes = bytesToString(arrenc);
                String des = new String(desencriptado);
                System.out.println("Desencriptando bytes: " + bytesToString(desencriptado));
                System.out.println("Cadena desencriptada: " + new String(desencriptado));
                
                String msjdesenc = new String(desencriptado);
                // byte[] arrdesencriptado = ld.decrypt(arrenc);
                //encriptarMensaje desm = new encriptarMensaje(msjentrada);
                //String mensajedesc = desm.desencriptamelo(bdes);
                txtLadoClienteVentana.setText(txtLadoClienteVentana.getText() + "\n Servidor: " + msjentrada);
                jTextArea1.setText(msjRsaD+ jTextArea1.getText() + "\n Mensaje descifrado (Bytes): " + bytes + "\n Mensaje descifrado: " + des + "\n N: " + msjRsaN + "\n D: " + "\n----------------------------------------------------------------------------------------------------------------------------------- ");

            }
        } catch (Exception e) {

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JTextArea jTextArea1;
    private static javax.swing.JTextArea txtLadoClienteVentana;
    private javax.swing.JTextField txtMensajeCliente;
    // End of variables declaration//GEN-END:variables
}
